### PR TITLE
[update] typing added to all functions and minor bug fixes

### PR DESCRIPTION
**Pull request by regmicmahesh**

### CODE REVIEW

**Comment by s0md3v** [comment]
What "minor bugs" does it fix? Please add a description.

**Comment by regmicmahesh** [comment]
the function get_otp_links can return None, if the condition defined in the function is not matched which is not handled and called replace on 'None' type ( called in line 113), which is fixed by checking if the value exists.

**Comment by s0md3v** [comment]
Thanks. Can we integrate this fix only? There's no need for type declaration.

**Comment by regmicmahesh** [comment]
sure.

**Comment by s0md3v** [comment]
With my change, the newline won't be included in this case:

```
elif otp_link:
    return otp_link
```

**Pull request merged**
